name: .NET CIWorkflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: false
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' 
    - name: Install MAUI workload
      run: dotnet workload install maui 
    - name: Restore dependencies
      run: dotnet restore eShop.Web.slnf /p:EnableiOSWorkload=false
    - name: Build
      run: dotnet build eShop.Web.slnf --configuration Release /p:EnableiOSWorkload=false /p:EnableMacCatalystWorkload=false      
    - name: Test
      run: dotnet test eShop.Web.slnf --no-build --verbosity normal

    
